-- Table for Users/Faculty
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  password TEXT NOT NULL
);

-- Table for Daily Reports
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  attendance_status TEXT NOT NULL,
  leave_reason TEXT,
  activities TEXT,
  in_time TEXT,
  out_time TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert original dummy data
INSERT INTO users (id, name, role, password) VALUES 
('admin', 'Netcom Admin', 'admin', 'netcom')
ON CONFLICT (id) DO NOTHING;

-- Disable RLS for now to mirror the exact behavior of your old SQLite backend (which had no security rules). 
-- You should enable and configure policies later!
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
